on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with:
          version: 12
          registry-url: 'https://registry.npmjs.org'
      - uses: shawnbot/npm-publish-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
